services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    command: ["tail", "-f"]
    volumes:
      - ./apps/client:/app

  sftp:
    build:
      context: .
      dockerfile: ./apps/sftp/Dockerfile
    volumes:
      - ./sftp-data:/home/user/upload
    command: user:password1:::upload
    ports:
      - "2222:22"