services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    command: ["tail", "-f"]
    volumes:
      - ./apps/client:/app

  sftp:
    build:
      context: .
      dockerfile: ./apps/sftp/Dockerfile
    volumes:
      - ./sftp-data:/home/user/upload
    command: user:password1:::upload
    ports:
      - "2222:22"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    restart: unless-stopped
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./azurite-data:/data
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data --debug /data/debug.log"